environment:
  name: prod
  project: cdf-bootcamp-66-prod
  type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: ${CDF_PROJECT} # ex. cdf-bootcamp-01-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      IDP_SCOPES: ${IDP_SCOPES} # replaced by .env
      # This is related to the cluster where the CDF project is hosted.
      CDF_URL: ${CDF_URL} # replaced by .env
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
      # Groups
      # OBJECT ID FOR PROD DATA PIPELINE OEE ENTRA GROUP
      data_developer_source_id: d22b4640-6727-49c9-9e47-1e4b733b0031
      data_pipeline_oee_source_id: e23d573d-91b0-4332-9ccf-d4e3d846437e
      # OBJECT ID FOR PROD ADMIN TK ENTRA GROUP
      readwrite_source_id: f1cb9710-7f08-4476-a5f4-cf67fb8b41fe
      # OBJECT ID FOR PROD ADMIN TK ENTRA GROUP
      readonly_source_id: f1cb9710-7f08-4476-a5f4-cf67fb8b41fe
      # OBJECT ID FOR PROD ICAPI EXTRACTORS ENTRA GROUP
      icapi_extractors_source_id: 792d5a96-9530-41cb-a525-f2b29e78b4d1
      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
